version: '3'
services:
  licode:
    image: licode:dev
    ports:
      - 3001:3001
      - 80:80
      - 443:443
    volumes:
      - ./config/nginx.conf:/etc/nginx/sites-enabled/default
      - ./cert/:/opt/cert/